import { type ArchitectureTemplate, MaestroLayer, DEFAULT_EDGE_METADATA } from "./types";

export const ARCHITECTURE_TEMPLATES: ArchitectureTemplate[] = [
  {
    id: "rag-pipeline",
    name: "RAG Pipeline",
    description:
      "Retrieval-Augmented Generation pipeline with user, LLM, vector store, and external data source.",
    nodes: [
      {
        position: { x: 100, y: 50 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 100, y: 200 },
        type: "agentComponent",
        data: {
          label: "LLM / Foundation Model",
          description: "Core language model for generation",
          category: "kc1",
          componentId: "kc1",
          maestroLayers: [MaestroLayer.FoundationModels],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 350, y: 200 },
        type: "dataStore",
        data: {
          label: "Vector Store",
          description: "Embeddings database for retrieval",
          category: "kc4",
          componentId: "kc4",
          maestroLayers: [MaestroLayer.DataOperations],
          trustLevel: "trusted",
          threats: [],
        },
      },
      {
        position: { x: 350, y: 50 },
        type: "actor",
        data: {
          label: "External Data Source",
          category: "external",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "User Query",
          encrypted: true,
          authentication: "OAuth2",
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Embedding Query", encrypted: true, threats: [] },
      },
      {
        source: "3",
        target: "2",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Data Ingestion",
          encrypted: false,
          authentication: "None",
          threats: [],
        },
      },
      {
        source: "2",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Retrieved Context",
          encrypted: true,
          threats: [],
        },
      },
    ],
  },
  {
    id: "multi-agent",
    name: "Multi-Agent System",
    description: "Orchestrator agent coordinating specialist agents with tool access.",
    nodes: [
      {
        position: { x: 250, y: 30 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 170 },
        type: "agentComponent",
        data: {
          label: "Orchestrator Agent",
          description: "Coordinates sub-agents",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 50, y: 340 },
        type: "agentComponent",
        data: {
          label: "Research Agent",
          description: "Performs information retrieval",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 340 },
        type: "agentComponent",
        data: {
          label: "Coding Agent",
          description: "Writes and executes code",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 50, y: 500 },
        type: "agentComponent",
        data: {
          label: "Web Search Tool",
          description: "Internet search capability",
          category: "kc5",
          componentId: "kc5",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 500 },
        type: "agentComponent",
        data: {
          label: "Code Executor",
          description: "Sandboxed code execution",
          category: "kc6",
          componentId: "kc6",
          maestroLayers: [MaestroLayer.DeploymentInfrastructure],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "User Request",
          encrypted: true,
          authentication: "OAuth2",
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Research Task", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "3",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Coding Task", encrypted: true, threats: [] },
      },
      {
        source: "2",
        target: "4",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Search Query",
          encrypted: true,
          authentication: "API Key",
          threats: [],
        },
      },
      {
        source: "3",
        target: "5",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Code to Execute", encrypted: true, threats: [] },
      },
    ],
  },
  {
    id: "simple-agent",
    name: "Simple Agent",
    description: "Basic agent with LLM, memory, and a single tool.",
    nodes: [
      {
        position: { x: 200, y: 30 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 200, y: 180 },
        type: "agentComponent",
        data: {
          label: "Agent",
          description: "Primary AI agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 430, y: 180 },
        type: "dataStore",
        data: {
          label: "Memory Store",
          description: "Agent conversation memory",
          category: "kc4",
          componentId: "kc4",
          maestroLayers: [MaestroLayer.DataOperations],
          trustLevel: "trusted",
          threats: [],
        },
      },
      {
        position: { x: 200, y: 350 },
        type: "agentComponent",
        data: {
          label: "LLM",
          description: "Foundation model",
          category: "kc1",
          componentId: "kc1",
          maestroLayers: [MaestroLayer.FoundationModels],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "User Message",
          encrypted: true,
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Store Memory", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "3",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "LLM Call", encrypted: true, threats: [] },
      },
    ],
  },
  {
    id: "sequential-pipeline",
    name: "Sequential Agent Pipeline",
    description:
      "Sequential processing pipeline with input validation, processing, and output verification.",
    nodes: [
      {
        position: { x: 50, y: 150 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 220, y: 150 },
        type: "agentComponent",
        data: {
          label: "Input Validator",
          description: "Validates and sanitizes input",
          category: "kc3",
          componentId: "kc3",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 400, y: 150 },
        type: "agentComponent",
        data: {
          label: "Processing Agent",
          description: "Core processing logic",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 400, y: 310 },
        type: "agentComponent",
        data: {
          label: "LLM",
          description: "Foundation model",
          category: "kc1",
          componentId: "kc1",
          maestroLayers: [MaestroLayer.FoundationModels],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 580, y: 150 },
        type: "agentComponent",
        data: {
          label: "Output Guard",
          description: "Filters and verifies output",
          category: "kc3",
          componentId: "kc3.2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "trusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Raw Input",
          encrypted: true,
          authentication: "OAuth2",
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Validated Input", encrypted: true, threats: [] },
      },
      {
        source: "2",
        target: "3",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "LLM Request", encrypted: true, threats: [] },
      },
      {
        source: "2",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Processed Output", encrypted: true, threats: [] },
      },
    ],
  },
  {
    id: "collaborative-swarm",
    name: "Collaborative Swarm",
    description: "Peer-to-peer multi-agent system with shared knowledge and consensus.",
    nodes: [
      {
        position: { x: 250, y: 30 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 100, y: 200 },
        type: "agentComponent",
        data: {
          label: "Agent Alpha",
          description: "Specialist agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 400, y: 200 },
        type: "agentComponent",
        data: {
          label: "Agent Beta",
          description: "Specialist agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 200 },
        type: "agentComponent",
        data: {
          label: "Agent Gamma",
          description: "Specialist agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 380 },
        type: "dataStore",
        data: {
          label: "Shared Knowledge Base",
          description: "Consensus memory",
          category: "kc4",
          componentId: "kc4",
          maestroLayers: [MaestroLayer.DataOperations],
          trustLevel: "trusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "3",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "User Task",
          encrypted: true,
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Agent Comm",
          encrypted: true,
          authentication: "mTLS",
          threats: [],
        },
      },
      {
        source: "2",
        target: "3",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Agent Comm",
          encrypted: true,
          authentication: "mTLS",
          threats: [],
        },
      },
      {
        source: "3",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Agent Comm",
          encrypted: true,
          authentication: "mTLS",
          threats: [],
        },
      },
      {
        source: "1",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Store Results", encrypted: true, threats: [] },
      },
      {
        source: "2",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Store Results", encrypted: true, threats: [] },
      },
      {
        source: "3",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Store Results", encrypted: true, threats: [] },
      },
    ],
  },
  {
    id: "reactive-agent",
    name: "Reactive Agent",
    description: "Event-driven agent reacting to external signals with tool execution.",
    nodes: [
      {
        position: { x: 50, y: 150 },
        type: "actor",
        data: {
          label: "Event Source",
          category: "external",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 150 },
        type: "agentComponent",
        data: {
          label: "Reactive Agent",
          description: "Event-driven agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 310 },
        type: "agentComponent",
        data: {
          label: "LLM",
          description: "Decision engine",
          category: "kc1",
          componentId: "kc1",
          maestroLayers: [MaestroLayer.FoundationModels],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 80 },
        type: "agentComponent",
        data: {
          label: "Action Tool",
          description: "Executes actions",
          category: "kc5",
          componentId: "kc5",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 230 },
        type: "dataStore",
        data: {
          label: "Event Log",
          description: "Audit trail",
          category: "kc4",
          componentId: "kc4",
          maestroLayers: [MaestroLayer.DataOperations, MaestroLayer.EvaluationObservability],
          trustLevel: "trusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Event Trigger",
          encrypted: true,
          authentication: "API Key",
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Decision Request", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "3",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Execute Action", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Log Event", encrypted: true, threats: [] },
      },
    ],
  },
  {
    id: "knowledge-intensive",
    name: "Knowledge-Intensive Agent",
    description: "Agent with rich knowledge retrieval across multiple data sources.",
    nodes: [
      {
        position: { x: 250, y: 30 },
        type: "actor",
        data: {
          label: "User",
          category: "actor",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 170 },
        type: "agentComponent",
        data: {
          label: "Knowledge Agent",
          description: "Research and synthesis agent",
          category: "kc2",
          componentId: "kc2",
          maestroLayers: [MaestroLayer.AgentFrameworks],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 250, y: 330 },
        type: "agentComponent",
        data: {
          label: "LLM",
          description: "Foundation model",
          category: "kc1",
          componentId: "kc1",
          maestroLayers: [MaestroLayer.FoundationModels],
          trustLevel: "semi-trusted",
          threats: [],
        },
      },
      {
        position: { x: 50, y: 330 },
        type: "dataStore",
        data: {
          label: "Vector DB",
          description: "Embeddings store",
          category: "kc4",
          componentId: "kc4.3",
          maestroLayers: [MaestroLayer.DataOperations],
          trustLevel: "trusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 330 },
        type: "dataStore",
        data: {
          label: "Knowledge Graph",
          description: "Structured knowledge",
          category: "kc4",
          componentId: "kc4.5",
          maestroLayers: [MaestroLayer.DataOperations],
          trustLevel: "trusted",
          threats: [],
        },
      },
      {
        position: { x: 450, y: 170 },
        type: "actor",
        data: {
          label: "External APIs",
          category: "external",
          maestroLayers: [MaestroLayer.AgentEcosystem],
          trustLevel: "untrusted",
          threats: [],
        },
      },
    ],
    edges: [
      {
        source: "0",
        target: "1",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "Query",
          encrypted: true,
          authentication: "OAuth2",
          containsPII: true,
          threats: [],
        },
      },
      {
        source: "1",
        target: "2",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "LLM Call", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "3",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Vector Search", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "4",
        type: "dataFlow",
        data: { ...DEFAULT_EDGE_METADATA, label: "Graph Query", encrypted: true, threats: [] },
      },
      {
        source: "1",
        target: "5",
        type: "dataFlow",
        data: {
          ...DEFAULT_EDGE_METADATA,
          label: "API Call",
          encrypted: true,
          authentication: "API Key",
          threats: [],
        },
      },
    ],
  },
];
