import { MaestroLayer } from "../types";

export interface MaestroThreatEntry {
  id: string;
  name: string;
  description: string;
  layer: MaestroLayer;
  severity: "critical" | "high" | "medium" | "low";
  tags: string[];
  mitigations: string[];
}

export const MAESTRO_THREAT_CATALOG: MaestroThreatEntry[] = [
  {
    id: "maestro-l1-adversarial",
    name: "Adversarial Examples",
    description:
      "Inputs crafted to fool the AI model into making incorrect predictions or behaving unexpectedly.",
    layer: MaestroLayer.FoundationModels,
    severity: "high",
    tags: ["tampering"],
    mitigations: [
      "Adversarial training",
      "Input validation and sanitization",
      "Model robustness testing",
    ],
  },
  {
    id: "maestro-l1-model-stealing",
    name: "Model Stealing / Extraction",
    description:
      "Attackers extract a copy of the AI model through API queries, resulting in IP theft.",
    layer: MaestroLayer.FoundationModels,
    severity: "high",
    tags: ["information-disclosure"],
    mitigations: [
      "Rate limiting on inference APIs",
      "Query pattern monitoring",
      "Watermarking models",
    ],
  },
  {
    id: "maestro-l1-backdoor",
    name: "Backdoor Attacks",
    description:
      "Hidden triggers within the AI model that cause malicious behavior when activated.",
    layer: MaestroLayer.FoundationModels,
    severity: "critical",
    tags: ["tampering", "privilege-escalation"],
    mitigations: [
      "Model provenance verification",
      "Backdoor detection scanning",
      "Supply chain security",
    ],
  },
  {
    id: "maestro-l1-poisoning",
    name: "Training Data Poisoning",
    description: "Injecting malicious data into the model training set to compromise behavior.",
    layer: MaestroLayer.FoundationModels,
    severity: "critical",
    tags: ["tampering"],
    mitigations: [
      "Data provenance tracking",
      "Training data validation",
      "Anomaly detection in training",
    ],
  },
  {
    id: "maestro-l1-membership-inference",
    name: "Membership Inference",
    description:
      "Determining whether specific data was used to train the model, potentially revealing private information.",
    layer: MaestroLayer.FoundationModels,
    severity: "medium",
    tags: ["information-disclosure"],
    mitigations: ["Differential privacy", "Output perturbation", "Access controls on model APIs"],
  },
  {
    id: "maestro-l1-dos",
    name: "DoS via Sponge Attacks",
    description:
      "Overwhelming foundation models with computationally expensive queries to exhaust resources.",
    layer: MaestroLayer.FoundationModels,
    severity: "medium",
    tags: ["denial-of-service"],
    mitigations: ["Rate limiting", "Query complexity analysis", "Resource quotas"],
  },
  {
    id: "maestro-l2-data-poisoning",
    name: "Data Poisoning (Operational)",
    description: "Manipulating operational data to compromise AI agent behavior.",
    layer: MaestroLayer.DataOperations,
    severity: "high",
    tags: ["tampering"],
    mitigations: ["Data integrity verification", "Input validation pipelines", "Anomaly detection"],
  },
  {
    id: "maestro-l2-rag-compromise",
    name: "Compromised RAG Pipelines",
    description: "Injecting malicious data into retrieval-augmented generation pipelines.",
    layer: MaestroLayer.DataOperations,
    severity: "high",
    tags: ["tampering", "information-disclosure"],
    mitigations: ["Source validation", "Content filtering", "RAG output verification"],
  },
  {
    id: "maestro-l2-data-exfiltration",
    name: "Data Exfiltration",
    description: "Stealing sensitive data stored in databases or data stores.",
    layer: MaestroLayer.DataOperations,
    severity: "high",
    tags: ["information-disclosure"],
    mitigations: ["Data loss prevention", "Access controls", "Encryption at rest", "Audit logging"],
  },
  {
    id: "maestro-l2-tampering",
    name: "Data Tampering in Transit",
    description: "Modifying AI data in transit or at rest, leading to incorrect agent behavior.",
    layer: MaestroLayer.DataOperations,
    severity: "medium",
    tags: ["tampering"],
    mitigations: ["Encryption in transit (TLS)", "Message authentication", "Integrity checksums"],
  },
  {
    id: "maestro-l3-supply-chain",
    name: "Supply Chain Attacks",
    description: "Targeting the AI framework dependencies, compromising software before delivery.",
    layer: MaestroLayer.AgentFrameworks,
    severity: "high",
    tags: ["tampering", "privilege-escalation"],
    mitigations: [
      "Dependency scanning",
      "SBOM management",
      "Pinned dependencies",
      "Signature verification",
    ],
  },
  {
    id: "maestro-l3-input-validation",
    name: "Input Validation Attacks",
    description:
      "Exploiting weaknesses in how the AI framework handles inputs, allowing injection.",
    layer: MaestroLayer.AgentFrameworks,
    severity: "high",
    tags: ["tampering", "privilege-escalation"],
    mitigations: ["Strict input validation", "Parameterized interfaces", "Sandboxed execution"],
  },
  {
    id: "maestro-l3-framework-evasion",
    name: "Framework Security Evasion",
    description: "AI agents designed to bypass security controls within the framework.",
    layer: MaestroLayer.AgentFrameworks,
    severity: "medium",
    tags: ["privilege-escalation"],
    mitigations: ["Defense-in-depth", "Runtime monitoring", "Behavioral analysis"],
  },
  {
    id: "maestro-l3-prompt-injection",
    name: "Prompt Injection via Framework",
    description: "Exploiting agent framework logic to inject malicious prompts.",
    layer: MaestroLayer.AgentFrameworks,
    severity: "critical",
    tags: ["tampering", "spoofing"],
    mitigations: [
      "Prompt hardening",
      "Input/output filtering",
      "Instruction hierarchy enforcement",
    ],
  },
  {
    id: "maestro-l4-container-compromise",
    name: "Compromised Container Images",
    description: "Malicious code injected into AI agent containers infecting production.",
    layer: MaestroLayer.DeploymentInfrastructure,
    severity: "high",
    tags: ["tampering", "privilege-escalation"],
    mitigations: [
      "Image scanning",
      "Signed images",
      "Registry access controls",
      "Runtime protection",
    ],
  },
  {
    id: "maestro-l4-lateral-movement",
    name: "Lateral Movement",
    description: "Attackers moving from one compromised AI infrastructure component to others.",
    layer: MaestroLayer.DeploymentInfrastructure,
    severity: "high",
    tags: ["privilege-escalation"],
    mitigations: ["Network segmentation", "Zero trust architecture", "Micro-segmentation"],
  },
  {
    id: "maestro-l4-resource-hijacking",
    name: "Resource Hijacking",
    description: "Compromised AI infrastructure used for cryptomining or illicit purposes.",
    layer: MaestroLayer.DeploymentInfrastructure,
    severity: "medium",
    tags: ["denial-of-service"],
    mitigations: ["Resource monitoring", "Anomaly detection", "Resource quotas"],
  },
  {
    id: "maestro-l4-iac-manipulation",
    name: "IaC Manipulation",
    description:
      "Tampering with infrastructure-as-code scripts to provision compromised resources.",
    layer: MaestroLayer.DeploymentInfrastructure,
    severity: "high",
    tags: ["tampering"],
    mitigations: ["IaC scanning", "Git signing", "Peer review", "Drift detection"],
  },
  {
    id: "maestro-l5-poisoned-observability",
    name: "Poisoned Observability Data",
    description: "Manipulating monitoring data to hide incidents from security teams.",
    layer: MaestroLayer.EvaluationObservability,
    severity: "high",
    tags: ["tampering", "repudiation"],
    mitigations: ["Immutable logging", "Log integrity verification", "Out-of-band monitoring"],
  },
  {
    id: "maestro-l5-data-leakage-logs",
    name: "Data Leakage through Observability",
    description: "Sensitive AI information exposed through logs or monitoring dashboards.",
    layer: MaestroLayer.EvaluationObservability,
    severity: "medium",
    tags: ["information-disclosure"],
    mitigations: ["Log sanitization", "PII redaction", "Access controls on dashboards"],
  },
  {
    id: "maestro-l5-detection-evasion",
    name: "Detection Evasion",
    description: "AI agents designed to avoid triggering alerts or being flagged by monitoring.",
    layer: MaestroLayer.EvaluationObservability,
    severity: "medium",
    tags: ["repudiation"],
    mitigations: ["Behavioral baselining", "Multi-signal detection", "Canary mechanisms"],
  },
  {
    id: "maestro-l5-metric-manipulation",
    name: "Evaluation Metric Manipulation",
    description:
      "Adversaries influencing benchmarks to favor their AI agents through biased test cases.",
    layer: MaestroLayer.EvaluationObservability,
    severity: "medium",
    tags: ["tampering"],
    mitigations: ["Independent evaluation datasets", "Red team testing", "Cross-validation"],
  },
  {
    id: "maestro-l6-compromised-security-agent",
    name: "Compromised Security AI Agents",
    description: "Attackers gaining control over AI security agents to disable protections.",
    layer: MaestroLayer.SecurityCompliance,
    severity: "critical",
    tags: ["privilege-escalation", "tampering"],
    mitigations: ["Multi-layer security", "Out-of-band verification", "Human oversight"],
  },
  {
    id: "maestro-l6-security-evasion",
    name: "Evasion of Security AI",
    description: "Adversarial techniques to bypass AI-based security controls.",
    layer: MaestroLayer.SecurityCompliance,
    severity: "high",
    tags: ["privilege-escalation"],
    mitigations: ["Adversarial robustness testing", "Ensemble detection", "Defense-in-depth"],
  },
  {
    id: "maestro-l6-regulatory-noncompliance",
    name: "Regulatory Non-Compliance",
    description: "AI agents operating in violation of privacy regulations or compliance standards.",
    layer: MaestroLayer.SecurityCompliance,
    severity: "high",
    tags: ["information-disclosure", "repudiation"],
    mitigations: ["Compliance monitoring", "Automated policy enforcement", "Regular audits"],
  },
  {
    id: "maestro-l7-agent-impersonation",
    name: "Agent Impersonation",
    description: "Malicious actors impersonating legitimate AI agents within the ecosystem.",
    layer: MaestroLayer.AgentEcosystem,
    severity: "high",
    tags: ["spoofing"],
    mitigations: [
      "Mutual authentication",
      "Agent identity verification",
      "Certificate-based trust",
    ],
  },
  {
    id: "maestro-l7-goal-manipulation",
    name: "Agent Goal Manipulation",
    description:
      "Attackers manipulating the intended goals of AI agents to pursue harmful objectives.",
    layer: MaestroLayer.AgentEcosystem,
    severity: "critical",
    tags: ["tampering", "privilege-escalation"],
    mitigations: [
      "Goal alignment verification",
      "Behavioral constraints",
      "Human-in-the-loop approval",
    ],
  },
  {
    id: "maestro-l7-tool-misuse",
    name: "Agent Tool Misuse",
    description: "AI agents manipulated to use tools in unintended harmful ways.",
    layer: MaestroLayer.AgentEcosystem,
    severity: "high",
    tags: ["privilege-escalation", "tampering"],
    mitigations: ["Tool sandboxing", "Permission boundaries", "Action auditing"],
  },
  {
    id: "maestro-l7-compromised-agents",
    name: "Compromised Agents in Ecosystem",
    description: "Malicious AI agents infiltrating the ecosystem posing as legitimate services.",
    layer: MaestroLayer.AgentEcosystem,
    severity: "high",
    tags: ["spoofing", "tampering"],
    mitigations: ["Agent registry validation", "Reputation systems", "Sandboxed interactions"],
  },
  {
    id: "maestro-l7-identity-attack",
    name: "Agent Identity Attack",
    description: "Compromising identity and authorization mechanisms of AI agents.",
    layer: MaestroLayer.AgentEcosystem,
    severity: "high",
    tags: ["spoofing", "privilege-escalation"],
    mitigations: ["Strong authentication", "Token rotation", "Least-privilege access"],
  },
];

export interface MaestroCrossLayerThreat {
  id: string;
  name: string;
  description: string;
  fromLayer: MaestroLayer;
  toLayer: MaestroLayer;
  severity: "critical" | "high" | "medium" | "low";
  triggerCondition: string;
}

export const MAESTRO_CROSS_LAYER_THREATS: MaestroCrossLayerThreat[] = [
  {
    id: "cross-l2-l7-goal-misalignment",
    name: "Goal Misalignment Cascade",
    description:
      "Data poisoning at Layer 2 causes goal misalignment propagating to agent behavior at Layer 7.",
    fromLayer: MaestroLayer.DataOperations,
    toLayer: MaestroLayer.AgentEcosystem,
    severity: "critical",
    triggerCondition: "Data store connected to agent component across trust boundary",
  },
  {
    id: "cross-l3-l7-supply-chain",
    name: "Supply Chain Compromise Propagation",
    description: "Compromised framework component at Layer 3 affects agent ecosystem at Layer 7.",
    fromLayer: MaestroLayer.AgentFrameworks,
    toLayer: MaestroLayer.AgentEcosystem,
    severity: "high",
    triggerCondition: "Framework component connected to agent ecosystem component",
  },
  {
    id: "cross-l4-l2-lateral",
    name: "Infrastructure to Data Lateral Movement",
    description: "Attacker moves from compromised infrastructure to data operations.",
    fromLayer: MaestroLayer.DeploymentInfrastructure,
    toLayer: MaestroLayer.DataOperations,
    severity: "high",
    triggerCondition: "Infrastructure component connected to data component",
  },
  {
    id: "cross-l1-l7-model-behavior",
    name: "Foundation Model Compromise to Ecosystem Impact",
    description: "Backdoor in foundation model leads to compromised agent behavior in ecosystem.",
    fromLayer: MaestroLayer.FoundationModels,
    toLayer: MaestroLayer.AgentEcosystem,
    severity: "critical",
    triggerCondition:
      "Foundation model connected (directly or transitively) to ecosystem component",
  },
  {
    id: "cross-l5-l6-observability-security",
    name: "Observability Blindness Enables Security Bypass",
    description:
      "Compromised observability at Layer 5 prevents detection of security violations at Layer 6.",
    fromLayer: MaestroLayer.EvaluationObservability,
    toLayer: MaestroLayer.SecurityCompliance,
    severity: "high",
    triggerCondition: "Observability component connected to security component",
  },
];

export const COMPONENT_TO_MAESTRO_LAYERS: Record<string, MaestroLayer[]> = {
  kc1: [MaestroLayer.FoundationModels],
  "kc1.1": [MaestroLayer.FoundationModels],
  "kc1.2": [MaestroLayer.FoundationModels],
  "kc1.3": [MaestroLayer.FoundationModels],
  "kc1.4": [MaestroLayer.FoundationModels],
  kc2: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  "kc2.1": [MaestroLayer.AgentFrameworks],
  "kc2.2": [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  "kc2.3": [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  kc3: [MaestroLayer.AgentFrameworks],
  "kc3.1": [MaestroLayer.AgentFrameworks],
  "kc3.2": [MaestroLayer.AgentFrameworks],
  "kc3.3": [MaestroLayer.AgentFrameworks],
  "kc3.4": [MaestroLayer.SecurityCompliance, MaestroLayer.AgentFrameworks],
  kc4: [MaestroLayer.DataOperations],
  "kc4.1": [MaestroLayer.DataOperations],
  "kc4.2": [MaestroLayer.DataOperations],
  "kc4.3": [MaestroLayer.DataOperations],
  "kc4.4": [MaestroLayer.DataOperations],
  "kc4.5": [MaestroLayer.DataOperations],
  "kc4.6": [MaestroLayer.DataOperations],
  kc5: [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  "kc5.1": [MaestroLayer.AgentFrameworks],
  "kc5.2": [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  "kc5.3": [MaestroLayer.AgentFrameworks, MaestroLayer.AgentEcosystem],
  kc6: [MaestroLayer.DeploymentInfrastructure, MaestroLayer.DataOperations],
  "kc6.1": [MaestroLayer.DeploymentInfrastructure],
  "kc6.1.1": [MaestroLayer.DeploymentInfrastructure],
  "kc6.1.2": [MaestroLayer.DeploymentInfrastructure],
  "kc6.2": [MaestroLayer.DeploymentInfrastructure],
  "kc6.2.1": [MaestroLayer.DeploymentInfrastructure],
  "kc6.2.2": [MaestroLayer.DeploymentInfrastructure],
  "kc6.3": [MaestroLayer.DataOperations],
  "kc6.3.1": [MaestroLayer.DataOperations],
  "kc6.3.2": [MaestroLayer.DataOperations],
  "kc6.3.3": [MaestroLayer.DataOperations],
  "kc6.4": [MaestroLayer.DeploymentInfrastructure],
  "kc6.5": [MaestroLayer.DeploymentInfrastructure],
  "kc6.6": [MaestroLayer.DeploymentInfrastructure],
  "kc6.7": [MaestroLayer.DeploymentInfrastructure],
  actor: [MaestroLayer.AgentEcosystem],
  external: [MaestroLayer.AgentEcosystem],
  datastore: [MaestroLayer.DataOperations],
  "trust-boundary": [MaestroLayer.SecurityCompliance],
};
